name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  ## Ensure pytest is installed

      - name: Run Tests
        run: |
          pytest  

      - name: Build Docker Image
        run: |
          docker build -t arogbonlo/flask-app .
        env:
          DOCKER_BUILDKIT: 1

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push to Docker Hub
        run: |
          docker push arogbonlo/flask-app
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v4.0.0
      with:
        version: v1.31 

    - name: Set up Kustomize
      run: |
        KUSTOMIZE_VERSION=$(curl -s "https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest" | grep tag_name | cut -d '"' -f 4)
        KUSTOMIZE_BIN="kustomize_${KUSTOMIZE_VERSION#v}_linux_amd64"
        curl -LO "https://github.com/kubernetes-sigs/kustomize/releases/download/${KUSTOMIZE_VERSION}/${KUSTOMIZE_BIN}.tar.gz"
        tar xzf "${KUSTOMIZE_BIN}.tar.gz"
        sudo mv kustomize /usr/local/bin/
        kustomize version

    - name: Apply manifests
      run: kubectl apply -k .
