name: CI/CD Pipeline for GitOps with ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      run: |
        docker build -t .
        docker push 
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Manifest Repository
      uses: actions/checkout@v2

    - name: Update Kubernetes Manifests
      run: |
        sed -i 's|image: .*|image: arogbonlo/flask-app:latest|' apps/flask-app/deployment.yaml
      
    - name: Deploy Manifests to Minikube via ArgoCD
      run: |
        kubectl apply -f apps/flask-app/
